#!/bin/sh
. "$(dirname "$0")/common.sh"

echo "===\n>> Checking branch name..."

# Check branch protection
BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCHES="^(master|main)"

if [[ $BRANCH =~ $PROTECTED_BRANCHES ]]; then
  echo ">> Direct push to the $BRANCH branch are not allowed. Please choose a new branch name."
  exit 1
fi

echo ">> Finish checking branch name"
